name: EAML
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adjusttext
  - joblib
  - matplotlib>=3.1.1
  - numpy>=1.16.2
  - openjdk>=8.0.0
  - pandas>=0.24.1
  - pip>=20.0.2
  - pysam>=0.15.2
  - python>=3.7
  - scikit-learn>=0.24.2
  - scipy>=1.2.1
  - seaborn>=0.9.0
  - statsmodels>=0.10.1
  - tqdm
